"""Default workflow action registry catalog."""

from protrepair.workflow.planning.default_action_registry.capabilities import (
    BACKBONE_WINDOW_REFINEMENT_CAPABILITY,
    COMMITTED_PACKING_CAPABILITY,
    EXTERNAL_SPAN_RECONSTRUCTION_CAPABILITY,
    HEAVY_ATOM_COMPLETION_CAPABILITY,
    HYDROGEN_COMPLETION_CAPABILITY,
    LOCAL_REFINEMENT_CAPABILITY,
    RETAINED_NON_POLYMER_HYDROGEN_COMPLETION_CAPABILITY,
    STEREOCHEMISTRY_CORRECTION_CAPABILITY,
    TERMINAL_AUGMENTATION_CAPABILITY,
)
from protrepair.workflow.planning.default_action_registry.registry import (
    EXPLICIT_WORKFLOW_ACTION_REGISTRY,
    REQUEST_DRIVEN_WORKFLOW_ACTION_REGISTRY,
    WORKFLOW_ACTION_REGISTRY,
)

__all__ = [
    "BACKBONE_WINDOW_REFINEMENT_CAPABILITY",
    "COMMITTED_PACKING_CAPABILITY",
    "EXPLICIT_WORKFLOW_ACTION_REGISTRY",
    "EXTERNAL_SPAN_RECONSTRUCTION_CAPABILITY",
    "HEAVY_ATOM_COMPLETION_CAPABILITY",
    "HYDROGEN_COMPLETION_CAPABILITY",
    "LOCAL_REFINEMENT_CAPABILITY",
    "REQUEST_DRIVEN_WORKFLOW_ACTION_REGISTRY",
    "RETAINED_NON_POLYMER_HYDROGEN_COMPLETION_CAPABILITY",
    "STEREOCHEMISTRY_CORRECTION_CAPABILITY",
    "TERMINAL_AUGMENTATION_CAPABILITY",
    "WORKFLOW_ACTION_REGISTRY",
]
